name: Deploy to OSSRH

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Run publish
        env:
          ORG_GRADLE_PROJECT_repositoryUsername: ${{ secrets.repositoryUsername }}
          ORG_GRADLE_PROJECT_repositoryPassword: ${{ secrets.repositoryPassword }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.signingKey }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.signingPassword }}
        run: ./gradlew publish
